name: multiLineEvent
'on': push
jobs:
  new-job:
    runs-on: ubuntu-latest
    steps:
      - name: new-step
        run: echo "Hello World!"

'on1' : pull
jobss:
  new-job1:
    runs-on: ubuntu-latest
    steps:
      - name: new-step1
        run: echo "this is for pull"
