name : "Pipeline"
on :
 push : 
  branches : ["main"]
 
 pull_request :
  branches : ["main"] 


jobs :
 on-push :
  runs-on : ubuntu-latest
  steps :
   - name : "running on push"
     run : echo "push successfull"
 
 on-pull_request : 
  runs-on : ubuntu-latest
  steps :
   - name : "running on pull"
     run : echo "pull successfull"